language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2

git:
  depth: 5

install: true

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/grumphp run
